# Generated by Django 4.2.1 on 2023-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.TextField(choices=[(1, '版本发布'), (2, '使用说明')], verbose_name='类型'),
        ),
    ]
