# Generated by Django 4.2.1 on 2023-06-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_feedback_description_alter_notes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.IntegerField(choices=[(1, '版本发布'), (2, '使用说明')], verbose_name='类型'),
        ),
    ]
