# Generated by Django 4.2.1 on 2023-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(verbose_name='反馈信息'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='反馈标题'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='说明内容'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='说明标题'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.IntegerField(choices=[(1, '版本发布说明'), (2, '系统使用说明')], verbose_name='说明类型'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
