# Generated by Django 4.2.1 on 2023-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '本周工作汇总',
                'verbose_name_plural': '本周工作汇总',
            },
        ),
        migrations.CreateModel(
            name='TeamSta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '本周工作统计',
                'verbose_name_plural': '本周工作统计',
            },
        ),
    ]
