# Generated by Django 4.2.1 on 2023-06-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_plan', models.IntegerField(default=0, verbose_name='是否上周计划')),
                ('title', models.CharField(max_length=200, verbose_name='工作事项')),
                ('expected_start_time', models.DateTimeField(verbose_name='预计开始时间')),
                ('expected_end_time', models.DateTimeField(null=True, verbose_name='预计完成时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('for_who', models.CharField(blank=True, default='', max_length=100, verbose_name='提出人(对于非主线工作)')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详细记录')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.nature', verbose_name='工作性质')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.way', verbose_name='工作形式')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.zone', verbose_name='工作域')),
            ],
            options={
                'verbose_name': '本周工作',
                'verbose_name_plural': '本周工作',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work.log')),
            ],
            options={
                'verbose_name': '下周计划',
                'verbose_name_plural': '下周计划',
            },
            bases=('work.log',),
        ),
    ]
